### PR TITLE
foldLevel between 1 and 8

### PR DESCRIPTION
**Pull request by slavaGanzin**
I did tests. 8 is maximum folding level.

### CODE REVIEW

**Comment by t9md** [comment]
atom allows to 8 at maximum?
Strange why they limit this number.

**Comment by t9md** [comment]
https://github.com/atom/atom/blob/0060d47f43107c4af614d57a20c7729c7416a855/src/register-default-commands.coffee#L253-L255

Although they provide command upto 8 level.
It's just indent level, it theoretically be able to fold any indent level.

**Comment by slavaGanzin** [comment]
I don't search for references. I just try to increase fold level beyond 8 and appearance doesn't change.

I don't like this limit too.

**Comment by t9md** [comment]
tryit_js_ ___tryit

I checked now. And confirmed more than 8 level folding works
See that I can fold 10 indent level in above gif.

Anyway, I will fix it by my side.
Thanks for PR.

**Comment by t9md** [comment]
So my understanding is "there is no such limitation for foldable indent level".
So we should not limit it by narrow too.

**Comment by slavaGanzin** [comment]
@t9md ok. Thanks for your participation

**Pull request closed without merging**
